### ISSUE TITLE
Instance of 'Headers Iterator': type 'JavaScriptObject' is not a subtype of type 'Iterator0<any>'

### ISSUE THREAD

**Issue by xvrh** [Zekfad/fetch_client#10] opened 2023-09-19 20:50 UTC
I'm getting this error with the new Chrome 117

```
TypeError: Instance of 'Headers Iterator': type 'JavaScriptObject' is not a subtype of type 'Iterator0<any>'
    at Object.wrapException (chrome-extension://bpjhagkkjkejoamnbkldnahdabfldfao/popup.dart.js:1084:43)
    at Object._failedAsCheck (chrome-extension://bpjhagkkjkejoamnbkldnahdabfldfao/popup.dart.js:2595:15)
    at Rti._generalAsCheckImplementation [as _as] (chrome-extension://bpjhagkkjkejoamnbkldnahdabfldfao/popup.dart.js:2584:9)
    at Rti._installSpecializedAsCheck (chrome-extension://bpjhagkkjkejoamnbkldnahdabfldfao/popup.dart.js:2507:22)
    at Object.HeadersInstanceMembers_entries (chrome-extension://bpjhagkkjkejoamnbkldnahdabfldfao/popup.dart.js:8638:43)
    at chrome-extension://bpjhagkkjkejoamnbkldnahdabfldfao/popup.dart.js:23323:27
    at _wrapJsFunctionForAsync_closure.$protected (chrome-extension://bpjhagkkjkejoamnbkldnahdabfldfao/popup.dart.js:4016:15)
    at _wrapJsFunctionForAsync_closure.call$2 (chrome-extension://bpjhagkkjkejoamnbkldnahdabfldfao/popup.dart.js:14309:12)
    at _awaitOnObject_closure.call$1 (chrome-extension://bpjhagkkjkejoamnbkldnahdabfldfao/popup.dart.js:14297:32)
    at _RootZone.runUnary$2$2 (chrome-extension://bpjhagkkjkejoamnbkldnahdabfldfao/popup.dart.js:16853:18)
```

If I comment-out these lines it works
https://github.com/Zekfad/fetch_client/blob/6631e5b71c23f4ee89c9580ce45309975edea31b/lib/src/fetch_client.dart#L157-L158

It's not triggering all the time, I have to investigate to provide a reproducible example.

**Comment by Zekfad** [comment] 2023-09-19 21:40
Duplicate of #9 
This is an issue with sdk, tracked in https://github.com/dart-lang/sdk/issues/53532

**Closed by Zekfad** 2023-09-19 21:40 UTC
