### ISSUE TITLE
Error: Expected a value of type 'Iterator', but got one of type 'DomIterator'

### ISSUE THREAD

**Issue by bhaumik1111** [Zekfad/fetch_client#12] opened 2023-10-26 08:46 UTC
when i run project on chrome in debug mode it will through error at below second line 
client = FetchClient(mode: RequestMode.cors, streamRequests: true);
final response = await client.send(http.Request("GET", uri));

it works perfectly on release mode 

how to solve it??

**Comment by Zekfad** [comment] 2023-10-27 16:07
Upgrade to Dart 3.2 (or 3.2.0-21.0.dev)
Duplicate of #9

**Comment by vinokanthv** [comment] 2023-10-30 20:22
@Zekfad Mate I don't it works, Dart 3.2 is still beta and don't think its a good idea to use it in production

**Comment by Zekfad** [comment] 2023-10-30 21:16
I am somewhat working on a solution for this.
It's very messy because we have to support old language versions, as well as different interop versions due to recently became public Iterator class.
Ideally I'd like to study and migrate to new interop fully to make it compatible with future wasm, but that requires a lot of manual work.

**Comment by Zekfad** [comment] 2023-10-30 22:20
`fetch_api` 1.0.3 published, it is a last version with old/old-new interop, next I'm gonna use `dart:js_interop` and enforce Dart 3.2 in next version.

Current version will be the last one to support from 2.19 to 3.1 Dart versions.
Package public interface won't change, so it wont be breaking, but future versions will benefit from better underlying layer.

**Comment by bhaumik1111** [comment] 2023-10-31 07:07
when it will available it this issue solved??
i use flutter version 3.10.5 (dart 3.0.5)
is it works for me??
if not then pls give me step for solving this issue 

bcoz previously i said in release it works fine but got error from user that in opera browser streaming not workingin release mode

i am  new to flutter so can you provide me a brief solution?

**Comment by Zekfad** [comment] 2023-10-31 10:03
Fix published in dependency `fetch_api`, so you should run `dart pub upgrade` and `dart pub get` to update transitive dependencies.
Which streaming you mean, response stream or streaming request body? The later one requires http3 server to work.

**Comment by bhaumik1111** [comment] 2023-10-31 10:51
fetch_api is not present in my pubspec.yaml file

**Comment by Zekfad** [comment] 2023-10-31 22:38
It is a transitive dependency, it is one of `fetch_client` dependencies, read https://dart.dev/tools/pub/glossary#transitive-dependency , you just need to run `dart pub upgrade` and `dart pub get`.

**Comment by vinokanthv** [comment] 2023-11-01 00:33
@Zekfad What a legend, thank you so much :) works like a charm :D

**Closed** 2023-11-01 00:53 UTC
Labels: bug, duplicate

**Comment by bhaumik1111** [comment] 2023-11-01 04:10
@Zekfad thank you so much brother !! works perfectly. just this 2 command i needed?
dart pub upgrade
dart pub get

**Comment by Zekfad** [comment] 2023-11-01 07:41
Yes, that's enough to update transitive dependencies where fix is deployed.
